package com.jhernandez.backend.bazaar.domain.model;

/*
 * Enumeration of error codes used across the application.
 */
public enum ErrorCode {
    USER_EMAIL_REQUIRED("user.email.required"),
    USER_EMAIL_INVALID("user.email.invalid"),
    USER_EMAIL_EXISTS("user.email.duplicate"),
    USER_PASSWORD_REQUIRED("user.password.required"),
    USER_PASSWORD_INVALID("user.password.invalid"),
    USER_ROLE_REQUIRED("user.role.required"),
    USER_ROLE_INVALID("user.role.invalid"),
    USER_NAME_REQUIRED("user.names.required"),
    USER_SURNAMES_REQUIRED("user.surnames.required"),
    USER_ADDRESS_REQUIRED("user.address.required"),
    USER_CITY_REQUIRED("user.city.required"),
    USER_PROVINCE_REQUIRED("user.province.required"),
    USER_ZIPCODE_REQUIRED("user.zipcode.required"),
    USER_ZIPCODE_INVALID("user.zipcode.invalid"),
    USER_NOT_FOUND("user.not.found"),
    USER_SAVE_ERROR("user.save.error"),
    USER_ID_NOT_NULL("user.id.not.null"),
    USER_ALREADY_ENABLED("user.already.enabled"),
    USER_ALREADY_DISABLED("user.already.disabled"),
    USER_DISABLED("user.disabled"),
    MASTER_ADMIN_UPDATE("master.admin.update"),
    MASTER_ADMIN_DISABLE("master.admin.disable"),
    MASTER_ADMIN_DELETE("master.admin.delete"),
    CART_EMPTY("cart.empty"),
    CART_ITEM_NOT_FOUND("cart.product.not.found"),
    CART_ITEM_ALREADY_EXISTS("cart.product.already.exists"),
    CART_ITEM_FROM_OWN_SHOP("cart.product.from.own.shop"),
    SHOP_PRODUCT_ALREADY_EXISTS("shop.product.already.exists"),
    SHOP_PRODUCT_NOT_FOUND("shop.product.not.found"),
    FAVOURITE_PRODUCT_ALREADY_EXISTS("favourite.product.already.exists"),
    ORDER_NOT_FOUND("order.not.found"),
    ORDER_CONFIRM_ERROR("order.confirm.error"),
    ORDER_SHIP_ERROR("order.ship.error"),
    ORDER_DELIVER_ERROR("order.deliver.error"),
    ORDER_CANCEL_ERROR("order.cancel.error"),
    ORDER_RETURN_ERROR("order.return.error"),
    ORDER_STATUS_SAME("order.status.same"),
    PRODUCT_NAME_REQUIRED("product.name.required"),
    PRODUCT_DESCRIPTION_REQUIRED("product.description.required"),
    PRODUCT_INVALID_PRICE("product.invalid.price"),
    PRODUCT_INVALID_SHIPPING("product.invalid.shipping"),
    PRODUCT_INVALID_DISCOUNT_PRICE("product.invalid.discount.price"),
    PRODUCT_INVALID_DISCOUNT("product.invalid.discount"),
    PRODUCT_INVALID_STOCK("product.invalid.stock"),
    PRODUCT_INVALID_QUANTITY("product.invalid.quantity"),
    PRODUCT_IMAGE_REQUIRED("product.image.required"),
    PRODUCT_NO_CATEGORY("product.no.category"),
    PRODUCT_ID_NOT_NULL("product.id.not.null"),
    PRODUCT_LIST_NOT_NULL("product.list.not.null"),
    PRODUCT_NOT_FOUND("product.not.found"),
    PRODUCT_OWNER_DISABLED("product.owner.disabled"),
    PRODUCT_ALREADY_ENABLED("product.already.enabled"),
    PRODUCT_ALREADY_DISABLED("product.already.disabled"),
    PRODUCT_DISABLED("product.disabled"),
    PRODUCT_INSUFFICIENT_STOCK("product.insufficient.stock"),
    CATEGORY_NAME_REQUIRED("category.name.required"),
    CATEGORY_IMAGE_REQUIRED("category.image.required"),
    CATEGORY_NAME_EXISTS("category.name.duplicate"),
    CATEGORY_NOT_FOUND("category.not.found"),
    CATEGORY_ID_NOT_NULL("category.id.not.null"),
    CATEGORY_ALREADY_ENABLED("category.already.enabled"),
    CATEGORY_ALREADY_DISABLED("category.already.disabled"),
    CATEGORY_DISABLED("category.disabled"),
    CATEGORY_DEFAULT_UPDATE("category.default.update"),
    CATEGORY_DEFAULT_DISABLE("category.default.disable"),
    CATEGORY_DEFAULT_DELETE("category.default.delete"),
    IMAGE_NULL("image.null"),
    IMAGE_LIST_EMPTY("image.list.empty"),
    IMAGE_FILENAME_EMPTY("image.filename.empty"),
    IMAGE_URL_EMPTY("image.url.empty"),
    IMAGE_ERROR("image.error"),
    IMAGE_NOT_FOUND("image.not.found"),
    IMAGE_NOT_READABLE("image.not.readable"),
    IMAGE_DELETE_ERROR("image.delete.error"),
    REVIEW_ID_NOT_NULL("review.id.not.null"),
    REVIEW_NOT_FOUND("review.not.found"),
    REVIEW_ALREADY_EXISTS("review.already.exists"),
    PAYMENT_AMOUNT_INVALID("payment.amount.invalid"),
    PAYMENT_CURRENCY_INVALID("payment.currency.invalid"),
    PAYMENT_INTENT_FAILED("payment.intent.failed"),
    BACKUP_PATH_ERROR("backup.path.error"),
    BACKUP_SCRIPT_ERROR("backup.script.error"),
    BACKUP_NOT_FOUND("backup.not.found"),
    BACKUP_ID_NOT_NULL("backup.id.not.null"),
    BACKUP_RESTORE_ERROR("backup.restore.error"),
    MESSAGE_ID_NOT_NULL("message.id.not.null"),
    MESSAGE_NOT_FOUND("message.not.found"),
    AUTHENTICATION_CREDENTIALS_INVALID("authentication.credentials.invalid"),
    OPERATION_NOT_ALLOWED("operation.not.allowed");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}

